/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author CASA 2
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_insertar = new javax.swing.JPanel();
        lb_instertar = new javax.swing.JLabel();
        lb_identificacion = new javax.swing.JLabel();
        lb_color = new javax.swing.JLabel();
        lb_edad = new javax.swing.JLabel();
        txtf_marca = new javax.swing.JTextField();
        txtf_color = new javax.swing.JTextField();
        txtf_edad = new javax.swing.JTextField();
        btn_insertar = new javax.swing.JButton();
        lb_marca1 = new javax.swing.JLabel();
        txtf_Identificacion1 = new javax.swing.JTextField();
        Panel_consultar = new javax.swing.JPanel();
        lb_consultar = new javax.swing.JLabel();
        lb_identificador = new javax.swing.JLabel();
        lb_marca = new javax.swing.JLabel();
        lb_color1 = new javax.swing.JLabel();
        lb_edad1 = new javax.swing.JLabel();
        txtf_Identificacion = new javax.swing.JTextField();
        txtf_marca2 = new javax.swing.JTextField();
        txtf_color2 = new javax.swing.JTextField();
        txtf_edad2 = new javax.swing.JTextField();
        btn_buscar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_insertar.setBackground(new java.awt.Color(153, 255, 153));
        Panel_insertar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_instertar.setText("Insertar Vinos");

        lb_identificacion.setText("Identificacion:");

        lb_color.setText("Color");

        lb_edad.setText("Edad");

        btn_insertar.setText("Insertar");

        lb_marca1.setText("Marca");

        javax.swing.GroupLayout Panel_insertarLayout = new javax.swing.GroupLayout(Panel_insertar);
        Panel_insertar.setLayout(Panel_insertarLayout);
        Panel_insertarLayout.setHorizontalGroup(
            Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_insertarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_insertarLayout.createSequentialGroup()
                        .addGroup(Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_marca1)
                            .addComponent(lb_color))
                        .addGap(60, 60, 60)
                        .addGroup(Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_insertarLayout.createSequentialGroup()
                                .addComponent(txtf_marca, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                .addContainerGap())
                            .addComponent(txtf_color)))
                    .addGroup(Panel_insertarLayout.createSequentialGroup()
                        .addGroup(Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Panel_insertarLayout.createSequentialGroup()
                                .addComponent(lb_edad)
                                .addGap(67, 67, 67)
                                .addComponent(txtf_edad))
                            .addGroup(Panel_insertarLayout.createSequentialGroup()
                                .addComponent(lb_instertar)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(Panel_insertarLayout.createSequentialGroup()
                                .addComponent(lb_identificacion)
                                .addGap(18, 18, 18)
                                .addComponent(txtf_Identificacion1)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_insertarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_insertar)
                        .addGap(56, 56, 56))))
        );
        Panel_insertarLayout.setVerticalGroup(
            Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_insertarLayout.createSequentialGroup()
                .addComponent(lb_instertar)
                .addGap(36, 36, 36)
                .addGroup(Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_identificacion)
                    .addComponent(txtf_Identificacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_marca1))
                .addGap(31, 31, 31)
                .addGroup(Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_color)
                    .addComponent(txtf_color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(Panel_insertarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_edad)
                    .addComponent(txtf_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btn_insertar)
                .addGap(35, 35, 35))
        );

        getContentPane().add(Panel_insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 240, 380));

        Panel_consultar.setBackground(new java.awt.Color(153, 255, 153));
        Panel_consultar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lb_consultar.setText("Consultar Vinos");

        lb_identificador.setText("Identificador");

        lb_marca.setText("Marca");

        lb_color1.setText("Color");

        lb_edad1.setText("Edad");

        txtf_marca2.setEditable(false);

        txtf_color2.setEditable(false);

        txtf_edad2.setEditable(false);

        btn_buscar.setText("Buscar");

        javax.swing.GroupLayout Panel_consultarLayout = new javax.swing.GroupLayout(Panel_consultar);
        Panel_consultar.setLayout(Panel_consultarLayout);
        Panel_consultarLayout.setHorizontalGroup(
            Panel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_identificador)
                    .addComponent(lb_consultar)
                    .addComponent(lb_marca)
                    .addComponent(lb_color1)
                    .addComponent(lb_edad1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(Panel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtf_edad2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(txtf_color2)
                    .addComponent(txtf_marca2)
                    .addComponent(txtf_Identificacion))
                .addGap(16, 16, 16))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_consultarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_buscar)
                .addGap(65, 65, 65))
        );
        Panel_consultarLayout.setVerticalGroup(
            Panel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_consultarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_consultar)
                .addGap(24, 24, 24)
                .addGroup(Panel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_identificador)
                    .addComponent(txtf_Identificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(Panel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_marca)
                    .addComponent(txtf_marca2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(Panel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_color1)
                    .addComponent(txtf_color2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(Panel_consultarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_edad1)
                    .addComponent(txtf_edad2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(btn_buscar)
                .addGap(38, 38, 38))
        );

        getContentPane().add(Panel_consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 230, 380));

        btn_salir.setText("Salir");
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, 30));

        btn_limpiar.setText("Limpiar");
        getContentPane().add(btn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void blanquear_campos(){

    txtf_Identificacion1.setText("");
    txtf_color.setText("");
    txtf_edad.setText("");
    txtf_marca.setText("");

}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_consultar;
    private javax.swing.JPanel Panel_insertar;
    public javax.swing.JButton btn_buscar;
    public javax.swing.JButton btn_insertar;
    public javax.swing.JButton btn_limpiar;
    public javax.swing.JButton btn_salir;
    private javax.swing.JLabel lb_color;
    private javax.swing.JLabel lb_color1;
    private javax.swing.JLabel lb_consultar;
    private javax.swing.JLabel lb_edad;
    private javax.swing.JLabel lb_edad1;
    private javax.swing.JLabel lb_identificacion;
    private javax.swing.JLabel lb_identificador;
    private javax.swing.JLabel lb_instertar;
    private javax.swing.JLabel lb_marca;
    private javax.swing.JLabel lb_marca1;
    public javax.swing.JTextField txtf_Identificacion;
    public javax.swing.JTextField txtf_Identificacion1;
    public javax.swing.JTextField txtf_color;
    public javax.swing.JTextField txtf_color2;
    public javax.swing.JTextField txtf_edad;
    public javax.swing.JTextField txtf_edad2;
    public javax.swing.JTextField txtf_marca;
    public javax.swing.JTextField txtf_marca2;
    // End of variables declaration//GEN-END:variables
}
